### ISSUE TITLE
Test on MS Edge (URGENT - Needs testing)

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-live-chat-support#269] opened 2017-03-02 08:52 UTC
Reportedly, the chat box is not showing up

**Comment by patdumond** [comment] 2017-03-08 14:20
Works for me in Edge.
![2017-03-08_9-19-58](https://cloud.githubusercontent.com/assets/9320495/23707468/7ecf29e8-03e0-11e7-9b8c-dc55079678fb.png)

**Comment by JarekCodeCabin** [comment] 2017-03-08 14:38
Confirmed & tested. It works on Edge

**Comment by DylanCodeCabin** [comment] 2017-03-15 07:40
Closing this issue as it has been tested by multiple agents and it is working in edge from our tests

**Closed by DylanCodeCabin** 2017-03-15 07:40 UTC
